### ISSUE TITLE
Hi, why two version.

### ISSUE THREAD

**Issue by kaijieshi7** [FujitsuResearch/hoi_sg#2]
Hi, can I know why there are two versions of hico?

**Comment by KentaroTakemoto** [comment]
Thank you very much for your interest!

By two versions of hico, you mean [this](https://drive.google.com/open?id=1QZcJmGVlF9f4h-XLWe9Gkmnmj2z1gSnk) and [this](https://github.com/YueLiao/PPDM)  in the dataset setup?

If so, the latter one is made for efficient data-loading based on the former one. The HOI triplets themselves are same and the only difference is the format of annotations. For further details please refer to [the official repository of PPDM](https://github.com/YueLiao/PPDM).

We used the latter annotation files because the official repositories of HOTR, QPIC, and STIP uses them. 

We hope this answer will meet your questions, and we would appreciate it if you could let us know if we have misunderstood the intent of your question.

**Comment by kaijieshi7** [comment]
Sorry. I mean the number of images in the current HICO-DET-SG is different from your paper.

**Comment by KentaroTakemoto** [comment]
Sorry for the delay of this reply and thank you for clarifying your question.

The reason why the statistics of the HICO-DET-SG are different between the arXiv paper and the current version of this repository is that we updated the HICO-DET-SG (and also V-COCO-SG) after DistShift 2022 (the arXiv paper is a replication of the camera-ready manuscript for this workshop). Please use the current version for your own study.  

We plan to submit a revised version of the paper that reflects these changes to arXiv this week.  We would be grateful if you could refer to that version for more details.

**Comment by kaijieshi7** [comment]
Ok, thank you.
